/** Stable Signalyzed Standard diagnostic codes — v0 taxonomy. */

export const STANDARD_CODES = {
  EXPORT_FAILED: "STANDARD.EXPORT.FAILED",
  EXPORT_EMPTY_FILE: "STANDARD.EXPORT.EMPTY_FILE",
  EXPORT_BROKEN_PLACEHOLDER: "STANDARD.EXPORT.BROKEN_PLACEHOLDER",
  EXPORT_JSON_ARTIFACT: "STANDARD.EXPORT.JSON_ARTIFACT",
  EXPORT_SPACED_HEADING: "STANDARD.EXPORT.SPACED_HEADING",
  EXPORT_BLANK_PDF: "STANDARD.EXPORT.BLANK_PDF",
  LINKS_MISSING_EXPECTED: "STANDARD.LINKS.MISSING_EXPECTED",
  LINKS_DUPLICATE: "STANDARD.LINKS.DUPLICATE",
  LINKS_BROKEN: "STANDARD.LINKS.BROKEN",
  QA_CROSS_JOB_CONTAMINATION: "STANDARD.QA.CROSS_JOB_CONTAMINATION",
  QA_CONTAMINATION_ARTIFACT: "STANDARD.QA.CONTAMINATION_ARTIFACT",
  QA_ROLE_CONTAMINATION: "STANDARD.QA.ROLE_CONTAMINATION",
  QA_UNSUPPORTED_CLAIM: "STANDARD.QA.UNSUPPORTED_CLAIM",
  QA_SEVERE_BULLET_REGRESSION: "STANDARD.QA.SEVERE_BULLET_REGRESSION",
  AST_PARSE_FAILURE: "STANDARD.AST.PARSE_FAILURE",
  AST_MALFORMED_SOURCE: "STANDARD.AST.MALFORMED_SOURCE",
  STRUCTURE_EMPTY_BULLETS: "STANDARD.STRUCTURE.EMPTY_BULLETS",
  STRUCTURE_MISSING_CORE_SECTION: "STANDARD.STRUCTURE.MISSING_CORE_SECTION",
  PDF_LINK_EXTRACTION_WEAK: "STANDARD.PDF.LINK_EXTRACTION_WEAK",
  QA_ADVISORY_WARNING: "STANDARD.QA.ADVISORY_WARNING",
  AST_LOW_BULLET_PRESERVATION: "STANDARD.AST.LOW_BULLET_PRESERVATION",
  AST_SECTION_MISMATCH: "STANDARD.AST.SECTION_MISMATCH",
} as const;

export type StandardDiagnosticCode = (typeof STANDARD_CODES)[keyof typeof STANDARD_CODES];

/** Map export validator internal codes to standard codes. */
export function mapExportDiagnosticCode(code: string): StandardDiagnosticCode | null {
  switch (code) {
    case "empty_file":
      return STANDARD_CODES.EXPORT_EMPTY_FILE;
    case "broken_placeholder":
      return STANDARD_CODES.EXPORT_BROKEN_PLACEHOLDER;
    case "json_artifact":
    case "object_serialization_artifact":
      return STANDARD_CODES.EXPORT_JSON_ARTIFACT;
    case "spaced_heading":
      return STANDARD_CODES.EXPORT_SPACED_HEADING;
    case "blank_pdf":
      return STANDARD_CODES.EXPORT_BLANK_PDF;
    case "missing_expected_link":
      return STANDARD_CODES.LINKS_MISSING_EXPECTED;
    case "duplicate_link":
      return STANDARD_CODES.LINKS_DUPLICATE;
    case "broken_link":
      return STANDARD_CODES.LINKS_BROKEN;
    case "missing_expected_sections":
      return STANDARD_CODES.STRUCTURE_MISSING_CORE_SECTION;
    case "empty_bullet":
      return STANDARD_CODES.STRUCTURE_EMPTY_BULLETS;
    default:
      return null;
  }
}
